config/routes.rb
Rails.application.routes.draw do
  resources :contact_forms
  root 'contact_forms#index'

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  before_action :set_contact_form, only: [:show, :edit, :update, :destroy]

  # GET /contact_forms
  # GET /contact_forms.json
  def index
    @contact_forms = ContactForm.all
    @contact_form = ContactForm.new
  end

  # GET /contact_forms/1
  # GET /contact_forms/1.json
  def show
  end

  # GET /contact_forms/new
  def new
    @contact_form = ContactForm.new
  end

  # GET /contact_forms/1/edit
  def edit
  end

  # POST /contact_forms
  # POST /contact_forms.json
  def create
    @contact_form = ContactForm.new(contact_form_params)

    respond_to do |format|
      if @contact_form.save
        format.html { redirect_to @contact_form, notice: 'Contact form was successfully created.' }
        format.json { render :show, status: :created, location: @contact_form }
      else
        format.html { render :new }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_forms/1
  # PATCH/PUT /contact_forms/1.json
  def update
    respond_to do |format|
      if @contact_form.update(contact_form_params)
        format.html { redirect_to @contact_form, notice: 'Contact form was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_form }
      else
        format.html { render :edit }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_forms/1
  # DELETE /contact_forms/1.json
  def destroy
    @contact_form.destroy
    respond_to do |format|
      format.html { redirect_to contact_forms_url, notice: 'Contact form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_form
      @contact_form = ContactForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_form_params
      params.require(:contact_form).permit(:firstName, :lastName, :email, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/views/contact_forms/_form.html.erb
<div id="contactform">
      <h1> Contact me </h1>
      <%= form_for(@contact_form) do |f| %>
      <% if @contact_form.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

          <ul>
          <% @contact_form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <!-- <%= f.label :First_Name %> -->
        <br>
        <%= f.text_field :firstName, :id => "textboxid", :placeholder => "First Name" %>
      </div>
      <div class="field">
        <!-- <%= f.label :Last_Name %> -->
        <br>
        <%= f.text_field :lastName, :id => "textboxid", :placeholder => "Last Name"  %>
      </div>
      <div class="field">
        <!-- <%= f.label :Email %> -->
        <br>
        <%= f.email_field :email, :id => "textboxid", :placeholder => "Email"  %>
      </div>
      <div class="field">
        <!-- <%= f.label :Message %> -->
        <br>
        <%= f.text_area :message, :id => "textboxid-message", :placeholder => "Message"  %>
      </div>
      <div class="actions">
        <%= f.submit 'Contact Robby' %>
        <br>
      </div>
    <% end %>
</div>

app/views/contact_forms/edit.html.erb
<h1>Editing Contact Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_form %> |
<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/index.html.erb
<div id="nav" class="toggled">
  <ul id="menu" class="">
    <li id="home">Home</li>
    <li id="about">About</li>
    <li id="portfolio_link">Portfolio</li>
    <li id="contact">Contact</li>
  </ul>
</div>

<div id="body">
<p id="notice"><%= notice %></p>

<div id="top_div">
  <h1>Robert Tassy</h1>
  <div id="recommendation">
    <li>"<a href="https://www.linkedin.com/in/jessica-braid-70252085?authType=NAME_SEARCH&authToken=9ssB&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A302871026%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1458515994163%2Ctas%3Ajessica%20braid" target="_blank"><em>Robert’s hard work and dedication made him an integral part of the team.</em>" -Jessica Braid <img src="<%= asset_path('linkedin-icon-small.png') %>" height="20"></a></li>
    <li>"<a href="https://www.linkedin.com/in/amandamartin938?authType=NAME_SEARCH&authToken=_9GX&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A180180859%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1458516802935%2Ctas%3Aamanda%20mar" target="_blank"><em>Whenever I had an idea to surprise our team I would always go to Robert to help me put my plan into action.</em>" -Amanda Martin <img src="<%= asset_path('linkedin-icon-small.png') %>" height="20"></a></li>
    <li>"<a href="https://www.linkedin.com/in/christiangarcia?authType=NAME_SEARCH&authToken=6HaH&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A5981750%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1458516819390%2Ctas%3Achristian%20gar" target="_blank"><em>It is rare to find someone who, in such a short time, can create strong and lasting relationships. Robert is this type of individual.</em>" -Christian Garcia <img src="<%= asset_path('linkedin-icon-small.png') %>" height="20"></a></li>
  </div>
</div>

<div id="about-me">

  <div id="picture">
  </div>

  <div id="bio">
    <h2>a snippet of me.. </h2>
    <p>An entrepreneurial spirit with a media edge, Robert has over 10 years of multimedia experience, having started from a young age.
       His skills include video and audio production (recording and editing), vector-based graphic design, photography & editing, social media marketing,
       and full-stack web development (like the site you see here!).</p><br>
       <p>However, it is through Robert's softer skills that he seeks to influence others and continue building his career:
       <em>effective communication, teamwork & collaboration, problem solving, critical observation, and conflict resolution</em>.
       Using his leveled emotional intelligence, Robert enjoys flexing his people skills. </p>
      <br>
  </div>
</div>

<div id="portfolio">
  <h1>My Projects</h1>

      <div id="mywork">
        <ol>
          <li><a href="https://github.com/RobbyTassy/REPL-projects/blob/master/worldOfWyncraft.rb" target="_blank"><strong>World of Wyncraft</strong>
            <p>a two-player REPL game playable on Terminal.app that lets players
            with distinct health and attack points battle until one stands victorious.</a></p>
          </li>
          <li><a href="https://github.com/RobbyTassy/Voter_Sim/blob/master/robbyVoterSim2.rb" target="_blank"><strong>Voter Simulation</strong>
            <p>a REPL simuation that allows the user to register a voter or politician
            based on political affiliations by using CRUD (Create, Read,
            Update, Destroy) to store their record.</a></p>
          </li>
          <li><a href="https://github.com/RobbyTassy/REPL-projects/blob/master/TipCalculartor.rb" target="_blank"><strong>Tip Calculator</strong>
            <p>a REPL calculator that takes your total bill amount and calculates
            your tip amount and portion of the bill if you choose to split it with others.</a></p>
          </li>
        </ol>
        <ol>
          <li><a href="https://robbytodolist.herokuapp.com/" target="_blank"><strong>To Do List</strong>
            <p>a to do list that allows you to make new tasks, edit existing one, and mark as complete
            the ones that have already been completed.</a></p>
          </li>
          <li><a href="https://pacific-journey-97213.herokuapp.com/" target="_blank"><strong>Wyndex</strong>
            <p>Social media stalking just got easier. A web application that aggregates someone's
              social media posts and puts them on one web page place for you using Twitter and Slack API.</a></p>
          </li>
          <li><a href="https://mytravelpal.herokuapp.com/" target="_blank"><strong>TravelPal</strong>
            <p>You've got a pal in your pocket. This texting friend parses your travel expenses by breaking them down by cost, location, and
            category when you send a text to it. Using specific APIs, we break down your text into actionable insight.</a></p>
          </li>
        </ol>
    </div>
</div>


<div id="contact-me">
  <div id="formbox">
    <%= render 'form' %>
  </div>
    <ol id="socialmedia">
      <a href="https://github.com/robbytassy" target="_blank"><li id="socialmedia-list"><img src="<%= asset_path('black-github-icon.png') %>" alt="Github" height="100" width="100"></li></a>
      <a href="https://www.linkedin.com/in/roberttassy" target="_blank"><li id="socialmedia-list"><img src="<%= asset_path('black-linkedin-icon.png') %>" alt="Linkedin" height="100" width="100"></li></a>
      <a href="https://twitter.com/robbytassy" target="_blank"><li id="socialmedia-list"><img src="<%= asset_path('black-twitter-icon.png') %>" alt="Twitter" height="100" width="100"></li></a>
      <a href="https://www.facebook.com/Roberttassy" target="_blank"><li id="socialmedia-list"><img src="<%= asset_path('black-facebook-icon.png') %>" alt="Facebook" height="100" width="100"></li></a>
    </ol>
  </div>
  </div>
</div>


</div>

app/views/contact_forms/new.html.erb
<h1>New Contact Form</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @contact_form.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @contact_form.lastName %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_form.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_form.message %>
</p>

<%= link_to 'Edit', edit_contact_form_path(@contact_form) %> |
<%= link_to 'Back', contact_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
</head>
<body>

<%= yield %>


<!-- <script type="text/javascript" src="jquery-2.2.1.min.js"></script> -->
</body>
      <!-- <footer>Robert Tassy</footer> -->
</html>